### ISSUE TITLE
Is there any common way to do something like an --ignore-path option?

### ISSUE THREAD

**Issue by smonff** [mlawren/githook-perltidy#12]
Hi I use your tool and find it very useful.

Though, because I use auto-generated `dbicdump` classes, I have a problem because the top part of those files are not supposed to be modified therefore formatted.

I wish it would be possible to define a `--ignore-path` option so `perltidy` would just don't process this path when the hook is launched.

Any idea on how to do this or is it a feature idea? 

Thanks.

**Comment by mlawren** [comment]
On Tue Sep 10, 2019 at 03:44:17AM -0700, Sébastien Feugère wrote:
> Hi I use your tool and find it very useful.

Glad to hear!

> Though, because I use auto-generated `dbicdump` classes, I have a
> problem because the top part of those files are not supposed to be
> modified therefore formatted.

I'm just curious (as I don't know dbicdump) why should they not be
modified? Perl is Perl... no?

> I wish it would be possible to define a `--ignore-path` option so
> `perltidy` would just don't process this path when the hook is
> launched.
> 
> Any idea on how to do this or is it a feature idea? 

Option 1: Perl::Tidy lets you define sections that it should not
tidy[1]. By default they start with '#<<<' and end with '#>>>' (on
separate lines).  You could run a script (after you run dbicdump) to
modify your generated classes, inserting those in the appropriate
places. Or even inserting them at the very beginning and end of the
code sections.

Option 2: When you generate your classes and commit them you can use
`NO_GITHOOK_PERLTIDY=1 git commit` to prevent githook-perltidy from
running at all.

Option 1 is perhaps the most interesting because the "configuration" of
what not to tidy is in your repo (although it does mean changing how
they run dbicdump). Option 2 relies on each developer remembering to
change how they invoke Git, and that only works if you commit your
generated classes in isolation away from your real code - otherwise
your real code wouldn't get tidied either.

If neither of those are sufficient then I'll have a bit of a deeper
think.

Option 3: Feature request: Look for a githook-perltidy specific marker
inside the files not to be tidied.  Similar to the '#<<< ... #>>>'
above.

Option 4: Feature request: support .perltidyrc files in
sub-directories, where you could explictly set --notidy. That would be
a bit more complicated and would only cover entire directories and not
specific files.

I would discount adding a '--notidy-files' argument to githook-perltidy
at the moment because it would rely on everyone who checks the repo to
also modify their pre-commit hook.

Cheers,
Mark

[1] https://metacpan.org/pod/distribution/Perl-Tidy/bin/perltidy#-fs,-format-skipping

-- 
Mark Lawrence

**Comment by smonff** [comment]
Thanks for your answer.

It looks like more a `Perl::Tidy` + `dbicdump` issue than something strictly related to `githook-perltidy`. I am gonna search for help on other channels.

The thing with `dbicdump` is that it automatically generate a `DBIx::Class` representation of a database schema you pass the connection parameter to. By using this, you get a perfect ORM system that can be synced when changes occurs in the database schema. For allowing successive auto-generations, you have to keep things strictly as they got generated, from the first line of the file that contains those comments:

    # Created by DBIx::Class::Schema::Loader
    # DO NOT MODIFY THE FIRST PART OF THIS FILE

until a special area near the end that looks like that:

  # Created by DBIx::Class::Schema::Loader v0.07049 @ 2019-08-14 11:01:38
  # DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:PceJ1Upxm5o2AbOxVsMeSw
 
  # You can replace this text with custom code or comments, and it will be preserved on regeneration

Any change to the top area of the file would produce a different checksum on regeneration.

This is why the option 1 and 3 wouldn't work. Option 2 would do the trick for me because I don't work in a team so it doesn't create any trouble not committing the changes in clear isolation.

Sorry, I checked the documentation before asking, but read to fast and didn't understood about `NO_GITHOOK_PERLTIDY`. Thanks for your time, I'll add more references in the comments if I find something interesting for later reference.
